version: 0.1

run-as: root

env:
    shell: bash
	
    phases:
        build:
            run-as: root
            on-failure: ABORT
            commands:
                - mvn clean package
            finally:
                - ./demo.sh
				